"""add veggie field

Revision ID: 7c45870b7f77
Revises: 9965d51c9bc4
Create Date: 2023-08-23 11:32:10.849989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c45870b7f77'
down_revision = '9965d51c9bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vegetarian', sa.Boolean(), nullable=True))
        batch_op.drop_index('ix_recipe_image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index('ix_recipe_image_id', ['image_id'], unique=False)
        batch_op.drop_column('vegetarian')

    # ### end Alembic commands ###
