"""next migration

Revision ID: e69dee6ed82b
Revises: bc363d984be4
Create Date: 2023-09-20 21:29:01.873825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e69dee6ed82b'
down_revision = 'bc363d984be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.alter_column('instruction',
               existing_type=mysql.VARCHAR(length=140),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.alter_column('instruction',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=140),
               existing_nullable=True)

    # ### end Alembic commands ###
